<script>
    setTimeout(()=>{
        console.log("hacking wifi.. Please wait... ")
    }, 1000)
    try{
    console.log(rahul)
}
catch(err){
    console.log("Balle balle error found in our code"+err);
}
    setTimeout(()=>{
        console.log("fetching username and password..  ")
    }, 2000)

    setTimeout(()=>{
        console.log("hacking rahul's facebook id ... ")
    }, 3000)

    setTimeout(()=>{
        console.log("Username and password of Rahul (+919998464567).. Please wait... ")
    }, 4000)



// if this condition happens then the try block will not resolve the error 
// try{
// setTimeout(()=>{
// console.log(rahul)
// },100);

// }




</script>